### ISSUE TITLE
Volley: NoConnectionError

### ISSUE THREAD

**Issue by FacuEt** [tbert12/LincedIn-TallerII-App#46]
com.android.volley.NoConnectionError: java.net.ProtocolException: Unexpected status line:

**Comment by mlafroce** [comment]
Indicar pasos para replicar bug

**Comment by FacuEt** [comment]
Hay request que llegan al server y request que no!
Ejemplo /user/me siempre llega al server, pero /img/id_imagen no llega. por eso el response es vacío y larga la excepción.
Supongo es un problema de la cola de Volley, en algo estamos errando ahí.

Para poder ver la excepción basta con ingresar a la app. Una vez logueado al cargar el perfil seleccionar la imagen de perfil, luego de actualizarla al querer cargarla mediante el url lanza la excepción (que se atrapa en HttpRequestHelper línea 114)
